
- name : Create eBGP peers for VXLAN fabric
  ios_config:
    lines:
      - "neighbor {{ item.neighbor }} remote-as {{ item.remote_as }}"
      - "neighbor {{ item.neighbor }} ebgp-multihop 3"
      - "neighbor {{ item.neighbor }} update-source {{ item.update_source }}"
    parents:
      - "router bgp {{ bgp_as_number }}"
  with_items:
    - "{{ bgp_neighbors }}"
  when: 
    - item.afi == "l2vpn"
    - item.safi == "evpn"

- name : Create L2VPN EVPN Address Family
  ios_config:
    lines:
      - "address-family l2vpn evpn"
    parents:
      - "router bgp {{ bgp_as_number }}"

- name : Import VPNV4 Routes Into EVPN
  ios_config:
    lines:
      - "import vpnv4 unicast re-originate"
    parents:
      - "router bgp {{ bgp_as_number }}"
      - "address-family l2vpn evpn"

- name : Enable Both Communities for all L2VPN EVPN Neighbors
  ios_config:
    lines:
      - "neighbor {{ item.neighbor }} activate"
      - "neighbor {{ item.neighbor }} send-community both"
    parents:
      - "router bgp {{ bgp_as_number }}"
      - "address-family l2vpn evpn"
  with_items:
    - "{{ bgp_neighbors }}"
  when: 
    - item.afi == "l2vpn"
    - item.safi == "evpn"

- name : Define IPV4 Unicast AF/SAFI for each VRF
  ios_config:
    lines:
      - "address-family ipv4 vrf {{ item.name }}"
    parents:
      - "router bgp {{ bgp_as_number }}"
  with_items:
    - "{{ vrf_l3vni }}"

- name : Import L2VPN EVPN routes into IPV4 Unicast
  ios_config:
    lines:
      - "advertise l2vpn evpn"
      - "maximum-paths {{ bgp_max_paths }}"
    parents:
      - "router bgp {{ bgp_as_number }}"
      - "address-family ipv4 vrf {{ item.name }}"
  with_items:
    - "{{ vrf_l3vni }}"

- name : Configure the VXLAN UDP Port Value
  ios_config:
    lines:
      - "vxlan udp port 4789"

- name : Create the NVE Interface
  ios_interface:
    name: nve1
    state: present

- name : Configure NVE Interface
  ios_config:
    lines:
      - "no ip address"
      - "source-interface {{ item.interface }}"
      - "host-reachability protocol bgp"
    parents:
      - "interface nve1"
  with_items:
    - "{{ loopbacks }}"
  when: item.transport == "vxlan"

# By default, IOS-XE only uses L3 info for ECMP hashing
- name : Change ECMP Hashing Algorithm to Include Layer 4 Ports
  ios_config:
    lines:
      - "ip cef load-sharing algorithm include-ports source"

