
- name: Enable required features
  nxos_feature:
    feature: "{{ item.feature }}"
    state: enabled
  with_items: "{{ features }}"

- name: Enable BGP NVO EVPN
  nxos_evpn_global:
    nv_overlay_evpn: true

- name: CONFIGURE PHYSICAL L3 INTERFACES
  nxos_interface:
    interface: "{{ item.interface }}"
    mode: layer3
    admin_state: up
    mtu: 9216
    state: present
  with_items: "{{ underlay_interfaces }}"

- name: CONFIGURE LOOPBACK INTERFACES
  nxos_interface:
    interface: "{{ item.interface }}"
    state: present
  with_items: "{{ loopbacks }}"

- name: CONFIGURE INTERFACE IP ADDR
  nxos_l3_interface:
    name: "{{ item.interface }}"
    ipv4: "{{ item.addr }}/{{ item.mask }}"
    state: present
  with_items: 
  - "{{ loopbacks }}"
  - "{{ underlay_interfaces }}"

- name: CONFIGURE OSPF PROCESS ID AND AREA AND ROUTER ID
  nxos_ospf_vrf:
    ospf: "{{ ospf_process_id }}"
    router_id: "{{ router_id }}"
    state: present

- name: ASSOCIATE INTERFACES WITH OSPF PROCESS
  nxos_interface_ospf:
    interface: "{{ item.interface }}"
    ospf: "{{ ospf_process_id }}"
    area: "{{ ospf_area }}"
    state: present
  with_items: 
  - "{{ underlay_interfaces }}"
  - "{{ loopbacks }}"

- name: CONFIGURE OSPF INTERFACES NETWORK P2P
  nxos_config:
    lines: ip ospf network point-to-point
    parents:
      - 'interface {{ item.interface }}'
  with_items: "{{ underlay_interfaces }}"

- name: CONFIGURE PIM ANYCAST RP
  nxos_config:
    lines:
      - "ip pim anycast-rp {{ rp_address }} {{ item.address }}"
  with_items: "{{ multicast_interface }}"

- name: CONFIGURE PIM RP
  nxos_pim_rp_address:
    rp_address: "{{ rp_address }}"
    state: present

- name: CONFIGURE PIM INTERFACES
  nxos_pim_interface:
    interface: "{{ item.interface }}"
    sparse: true
    state: present
  when: item.role != "borderPE"
  with_items: "{{ underlay_interfaces }}"

- name: CONFIGURE BGP ASN AND ROUTER ID
  nxos_bgp:
    asn: "{{ vxlan_asn }}"
    router_id: "{{ router_id }}"
    state: present

- name: CONFIGURE BGP NEIGHBORS
  nxos_bgp_neighbor:
    asn: "{{ vxlan_asn }}"
    neighbor: "{{ item.neighbor }}"
    remote_as: "{{ item.remote_as }}"
    update_source: "{{ item.update_source }}"
    state: present
  with_items: "{{ bgp_neighbors }}"

- name: Enable L2VPN EVPN AFI/SAFI to BGP Neighbores
  nxos_bgp_neighbor_af:
    asn: "{{ vxlan_asn }}"
    neighbor: "{{ item.neighbor }}"
    afi: l2vpn
    safi: evpn
    send_community: both
    state: present
  with_items: "{{ bgp_neighbors }}"

- name: Configure L2VPN EVPN Route Reflectors for Fabric peers
  nxos_bgp_neighbor_af:
    asn: "{{ vxlan_asn }}"
    neighbor: "{{ item.neighbor }}"
    afi: l2vpn
    safi: evpn
    route_reflector_client: "true"
    state: present
  when: item.type == 'ibgp'
  with_items:
    - "{{ bgp_neighbors }}"

- name: Configure eBGP multi-hop for eBGP peers
  nxos_config:
    lines:
      - "ebgp-multihop 3"
    parents:
      - "router bgp {{ vxlan_asn }}"
      - "neighbor {{ item.neighbor }}"
  when: item.type == 'ebgp'
  with_items:
    - "{{ bgp_neighbors }}"

- name: Create Next Hop Unchanged Route Map
  nxos_config:
    lines:
      - "route-map set-next-hop-unchanged permit 10"

- name: Add Next Hop Unchanged Setting to Route Map
  nxos_config:
    lines:
      - "set ip next-hop unchanged"
    parents:
      - "route-map set-next-hop-unchanged permit 10"

- name: Set Next Hop Unchanged for eBGP L2VPN EVPN Peers
  nxos_config:
    lines:
      - "route-map set-next-hop-unchanged out"
    parents:
      - "router bgp {{ vxlan_asn }}"
      - "neighbor {{ item.neighbor }}"
      - "address-family l2vpn evpn"
  when: item.type == 'ebgp'
  with_items:
    - "{{ bgp_neighbors }}"
