
- name : Underlay interface and routing configuration 
  import_tasks: underlay.yml
  tags: remotePE_underlay

- name : VRF Tenant configuration
  import_tasks: tenants.yml
  tags: remotePE_tenants

- name : MPLS transport interface and control plane configuration
  import_tasks: mpls.yml
  tags: remotePE_mpls

