
- name: (NXOS) Set Switch Hostname
  nxos_config:
    lines: hostname {{ inventory_hostname }}

- name: (NXOS) Default switch interfaces to L3
  nxos_config:
    lines: no system default switchport

- name: (NXOS) Default switch interfaces to shutdown
  nxos_config:
    lines: system default switchport shutdown

- name: (NXOS) Enable scp server
  nxos_feature:
    feature: scp-server
    state: enabled

