---

router_id: 192.168.3.12

# lo0 - MPLS/EVPN BGP Peering
# lo1 - VTEP functions
loopbacks:
  - interface: loopback0
    addr: 192.168.3.12
    mask: 32
    protocol: eigrp
    transport: mpls
  - interface: loopback1
    addr: 192.168.0.12
    mask: 32
    protocol: ospf
    transport: vxlan

# Links to VXLAN spine-1 (Gi14) and spine-2 (Gi15)
# Links to MPLS remotePE-1 (Gi11) and remotePE-2 (Gi12)
underlay_interfaces:
  - interface: GigabitEthernet14
    addr: 192.168.112.2
    mask: 30
    protocol: ospf
    transport: vxlan
  - interface: GigabitEthernet15
    addr: 192.168.122.2
    mask: 30
    protocol: ospf
    transport: vxlan
  - interface: GigabitEthernet11
    addr: 192.168.221.1
    mask: 30
    protocol: eigrp
    transport: mpls
  - interface: GigabitEthernet12
    addr: 192.168.222.1
    mask: 30
    protocol: eigrp
    transport: mpls
