---

router_id: 192.168.3.11

# lo0 - EVPN BGP Peering
# lo1 - VTEP functions
# lo2 - MPLS BGP Peering
loopbacks:
  - interface: loopback0
    addr: 192.168.3.11
    mask: 32
    protocol: ospf
    transport: vxlan
  - interface: loopback1
    addr: 192.168.0.11
    mask: 32
    protocol: ospf
    transport: vxlan
  - interface: loopback2
    addr: 192.168.3.111
    mask: 32
    protocol: eigrp
    transport: mpls

# Links to VXLAN spine-1 (Gi7) and spine-2 (Gi8)
# Links to MPLS remotePE-1 (Gi2) and remotePE-2 (Gi3)
underlay_interfaces:
  - interface: GigabitEthernet7
    addr: 192.168.111.2
    mask: 30
    protocol: ospf
    transport: vxlan
  - interface: GigabitEthernet8
    addr: 192.168.121.2
    mask: 30
    protocol: ospf
    transport: vxlan
  - interface: GigabitEthernet2
    addr: 192.168.211.1
    mask: 30
    protocol: eigrp
    transport: mpls
  - interface: GigabitEthernet3
    addr: 192.168.212.1
    mask: 30
    protocol: eigrp
    transport: mpls
  - interface: GigabitEthernet4
    addr: 192.168.201.1
    mask: 30
    protocol: eigrp
    transport: mpls
