---

router_id: 192.168.3.22

# lo0 - MPLS/EVPN BGP Peering
loopbacks:
  - interface: loopback0
    addr: 192.168.3.22
    mask: 32
    protocol: eigrp
    transport: mpls

# Links to MPLS borderPE-1 (Gi2) and borderPE-2 (Gi3)
# Link for MPLS between remotePE (Gi4)
underlay_interfaces:
  - interface: GigabitEthernet2
    addr: 192.168.212.2
    mask: 30
    protocol: eigrp
    transport: mpls
  - interface: GigabitEthernet3
    addr: 192.168.222.2
    mask: 30
    protocol: eigrp
    transport: mpls
  - interface: GigabitEthernet4
    addr: 192.168.202.2
    mask: 30
    protocol: eigrp
    transport: mpls

# The Router SVI IP Address for every VRF
mpls_pe_address: 12.0.0.1
mpls_pe_netmask: 255.255.255.0
