---

router_id: 192.168.1.1

# lo0 = iBGP EVPN Route Reflector
# lo1 = Multicast Anycast Rendezvous Point (RP)
loopbacks:
  - { interface: loopback0, addr: 192.168.1.1, mask: 32 }
  - { interface: loopback1, addr: 192.168.0.100, mask: 32 }

# Leaf links
underlay_interfaces:
  # VXLAN Fabric Links
  - interface: Ethernet1/1
    addr: 192.168.11.1
    mask: 30
    role: leaf
  - interface: Ethernet1/2
    addr: 192.168.12.1
    mask: 30
    role: leaf
  # BorderPE Links
  - interface: Ethernet1/8
    addr: 192.168.111.1
    mask: 30
    role: borderPE
  - interface: Ethernet1/9
    addr: 192.168.112.1
    mask: 30
    role: borderPE

