---

router_id: 192.168.1.2

# lo0 = iBGP EVPN Route Reflector
# lo1 = Multicast Anycast Rendezvous Point (RP)
loopbacks:
  - { interface: loopback0, addr: 192.168.1.2, mask: 32 }
  - { interface: loopback1, addr: 192.168.0.100, mask: 32 }

# Leaf links
underlay_interfaces:
  # VXLAN Fabric Links
  - interface: Ethernet1/1
    addr: 192.168.21.1
    mask: 30
    role: leaf
  - interface: Ethernet1/2
    addr: 192.168.22.1
    mask: 30
    role: leaf
  # BorderPE Links
  - interface: Ethernet1/7
    addr: 192.168.121.1
    mask: 30
    role: borderPE
  - interface: Ethernet1/8
    addr: 192.168.122.1
    mask: 30
    role: borderPE
